name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout source Git branch
        uses: actions/checkout@v7

      - name: 🐇 Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: 🛠️ Install dependencies
        run: bun install

      - name: 🧪 Run tests
        run: bun run test

      - name: 🏗️ Build static pages
        run: bun run build

      - name: 🧑‍🔧 Setup Pages
        uses: actions/configure-pages@v6

      - name: 📤 Uploading artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "."

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 🚢 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
      - name: 🫠 This job's status is ${{ job.status }}.
        run: echo "🫠 This job's status is ${{ job.status }}."
      - name: 🌐 Deployed to ${{ steps.deployment.outputs.page_url }}.
        run: echo "🌐 Deployed to ${{ steps.deployment.outputs.page_url }}."
