on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v4
        with:
            ref: master
            fetch-depth: 10
            submodules: true

      - name: Remove sourcemapped CSS.
        run: rm css -r
      
      - name: Make a new production CSS directory
        run: mkdir css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: scss/ahoylemon.scss
          destination: css/ahoylemon.css